version: "3"

services:
    node_app:
        build: .
        container_name: node_app
        command: "npm start"
        ports:
            - "3000:3000"
        volumes: 
            - .:/usr/app
        depends_on: 
            - database

    database:
        container_name: database
        image: postgres:11
        ports: 
            - "5432:5432"
        expose: 
            - "5432"
        volumes: 
            - postgres:/data
        environment: 
            POSTGRES_DB: ${DB}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes: 
    postgres:   